server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:        
     security:
       user:
         name: admin
         password: admin
         
 spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: admin
        platform: mysql
        url: jdbc:mysql://localhost/bancoBD?useTimezone=true&serverTimezone=UTC
        username: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
